package com.blikeng.job.executor.domain;

public enum JobType {
    ADD_NUMBERS,
    COUNT_WORDS,
    ANALYZE_FILE,
    EXTRACT_METADATA,
    HASH_FILE,
    HASH_TEXT,
    COMPARE_HASHES,
    COMPRESS_FILE,
    DECOMPRESS_FILE,
    COMPRESS_TEXT,
    DECOMPRESS_TEXT,

    ENCRYPT_FILE,
    DECRYPT_FILE,
    ENCRYPT_TEXT,
    DECRYPT_TEXT,
}